<?php require_once("views/template/header.phtml"); ?>
<?php require_once("views/template/changeProfilePicture.phtml"); ?>
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<div class="container">
    <div class="row bg-light mt-3">
        <div class="col">
            <img class="mb-1 mt-1" src=<?=$view->avatarPath?> width="80em" height="80em" style='border-radius: 45px; border:1px solid cornflowerblue'/>
        </div>
        <div class="col">
            <div>
                <?php if($view->isOwner):?>
                    <button type="button" class="btn btn-success btn-sm mt-2 mb-2 ml-2 float-right" data-toggle="modal" data-target="#profilePictureModal">Change Picture</button>
                <?php else:?>
                    <?php if($view->isFriend):?>
                        <button id="addFriendButton" type="button" onclick="addFriend()" class="btn btn-primary btn-sm mt-2 mb-2 float-right">Remove Friend</button>
                    <?php else:?>
                        <button id="addFriendButton" type="button" onclick="addFriend()" class="btn btn-primary btn-sm mt-2 mb-2 float-right">Add Friend</button>
                    <?php endif;?>
                <?php endif;?>
            </div>
        </div>
    </div>
    <div class="row bg-light">
        <h3 class="display-4 ml-3" style="font-size: 1.2em;"><?=$view->Name?></h3>
    </div>
    <div class="row bg-light">
        <small class="text-muted ml-3">Birthday - <?=$view->Birthday?></small>

    </div>
    <div class="row bg-light mb-3">
        <small class="text-muted mb-1 ml-3">Account Created - <?=$view->TimeCreated?></small>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-3 bg-light">
            <h4 class="mt-1 mb-1" id="friendsNumberText">Connected with - </h4>
            <!-- Populated with js !-->
            <div id="friendsList" class="container">
                <div class="loader"></div>
            </div>
            <button type="button" class="btn btn-primary btn-sm mb-1 mt-3" onclick="updateFriendList()">Refresh</button>
            <button type="button" class="btn btn-secondary btn-sm mb-1 mt-3">View All</button>
            <script type="module" src="scripts/populateProfileFriends.js"></script>
        </div>

        <div class="col-1"></div>

        <div class="col-8 bg-light">
            <?php if($view->isOwner):?>
                <h4 class="mt-2" style="display: inline-block">New Post</h4>
                <div id="editor-container" class="mt-2 mb-2" style="height: 15em">
                </div>
                <script src="scripts/postQuill.js"></script>
                <button type="button" class="btn btn-primary btn-sm mb-2" onclick="addPost()">Post</button>
            <?php else:?>
                <h4 class="mt-2" style="display: inline-block">Chat with <?=$view->Name?></h4>
                <div id="chatWindow" class="mb-2" style="border: 2px solid black; overflow: scroll; height: 12em;">
                    <div class="loader"></div>
                </div>
                <div id="isTyping"></div>
                <div id="editor-container" class="mt-2 mb-2" style="height: 4em"></div>
                <script type="module" src="scripts/messengerChat.js"></script>
                <button type="button" class="btn btn-primary btn-sm mb-2" onclick="sendChatMessage()">Send Message</button>
                <button type="button" class="btn btn-danger btn-sm mb-2">Report to site admin</button>
            <?php endif;?>
            <script type="module" src="scripts/generatePosts.js"></script>
        </div>
    </div>

    <div id="postArea" class="row mt-4">
        <div class="loader"></div>
    </div>
</div>

<script type="module" src="scripts/addFriend.js"></script>
<?php require_once("views/template/footer.phtml"); ?>
