<?php require_once("views/template/header.phtml"); ?>

<div class="container bg-light mt-3" style="max-width: 20em">
    <div class="text-center">
        <h4 class="mb-3 text-primary mt-3" style="display: inline-block">Forgot Password?</h4>
    </div>

    <?php if($view->Error !== ""):?>
        <div class="text-center alert alert-danger" role="alert">
            <?=$view->Error?>
        </div>
    <?php endif;?>

    <form method="post" class="text-left">
        <div class="form-group mt-2">
            <label for="inputPassword">New password</label>
            <input type="password" class="form-control" id="inputPassword" name="inputPassword" aria-describedby="password" placeholder="New Password">
        </div>

        <div class="form-group mt-2">
            <label for="inputPasswordConfirm">Confirm Password</label>
            <input type="password" class="form-control" id="inputPasswordConfirm" name="inputPasswordConfirm" aria-describedby="password" placeholder="Confirm Password">
        </div>

        <div class="text-center">
            <button type="submit" name="submit" class="btn btn-primary mb-2 mt-2">Submit</button>
        </div>

    </form>
</div>

<?php require_once("views/template/footer.phtml"); ?>
